; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200
upload_speed = 921600
platform = espressif32
framework = arduino
; https://registry.platformio.org/tools/espressif/toolchain-riscv32-esp/versions
;platform_packages = espressif/toolchain-riscv32-esp
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder
build_flags = 
    !python scripts/build_flags.py git_branch
    !python scripts/build_flags.py git_repo
    !python scripts/build_flags.py git_owner
    -D GITHUB_RUN=\"${sysenv.GITHUB_RUN}\"
;    -D WIFISSID=\"gast\"             ; use fixed WiFi credentials if Improv-WiFi-Library isn´t supported by your board
;    -D WIFIPASSWORD=\"12345678\"     ; use fixed WiFi credentials if Improv-WiFi-Library isn´t supported by your board
    -Wall -Wextra
    -D CONFIG_ARDUHAL_LOG_COLORS
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D WS_MAX_QUEUED_MESSAGES=128
    -D WSL_HIGH_PERF
lib_deps = 
    knolleary/PubSubClient
    bblanchon/ArduinoJson@>6.19.0
    EinarArnason/ArduinoQueue
    https://github.com/bblanchon/ArduinoStreamUtils.git
    https://github.com/YiannisBourkelis/Uptime-Library.git
    https://github.com/tobiasfaust/Improv-WiFi-Library.git
    https://github.com/tobiasfaust/ElegantOTA.git
    https://github.com/tobiasfaust/esp-handlefiles.git
    https://github.com/tobiasfaust/webserial.git
    ;https://github.com/ESP32Async/ESPAsyncWebServer#v3.6.0  #still imported from ElegantOTA
    

[env:firmware_ESP32]
board = esp32dev

[env:firmware_ESP32-S2]
board = esp32-s2-saola-1

[env:firmware_ESP32-S3]
board = esp32-s3-devkitc-1

[env:firmware_ESP32-C3]
board = esp32-c3-devkitm-1
build_flags = ${env.build_flags}
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D DEFAULT_MODBUS_RX_PIN=6
    -D DEFAULT_MODBUS_TX_PIN=7
